version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3333:3333"
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        command: npm run dev
        networks:
            - app-network
        depends_on:
            - postgres

    postgres:
        image: postgres:15.3-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - crypto_pg_data:/postgresql
        networks:
            - app-network

volumes:
    crypto_pg_data:
    node_modules:

networks:
  app-network:
    driver: bridge