version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3333:3333"
        environment:
            - STAGE = 'DEV'
            - SERVER_PORT = '3333'
            - JWT_KEY = 'secret'
            - CRYPTO_API_URL = 'https://www.mercadobitcoin.net/api/BTC/ticker/'
            - SALT_ROUNDS = '2'
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=cryptodb
            - DB_HOST=172.21.0.1
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        command: npm run dev
        networks:
            - app-network
        depends_on:
            - postgres

    postgres:
        image: postgres:15.3-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=cryptodb
        volumes:
            - crypto_pg_data:/postgresql
        networks:
            - app-network

volumes:
    crypto_pg_data:
    node_modules:

networks:
  app-network:
    driver: bridge